#!/bin/zsh
sed -i "s/xoldmat/mxold/g" *
sed -i "s/xnewmat/mxnew/g" *
sed -i "s/deltamat/mdelta/g" *
sed -i "s/weightmat/mweight/g" *
sed -i "s/dhatmat/mdhat/g" *
sed -i "s/basismat/mbasis/g" *
sed -i "s/distmat/mdist/g" *
sed -i "s/evecmat/mevec/g" *
sed -i "s/xauxmat/mxaux/g" *
sed -i "s/crossmat/mcross/g" *
sed -i "s/xoldvec/vxold/g" *
sed -i "s/xnewvec/vxnew/g" *
sed -i "s/deltavec/vdelta/g" *
sed -i "s/weightvec/vweight/g" *
sed -i "s/dhatvec/vdhat/g" *
sed -i "s/basisvec/vbasis/g" *
sed -i "s/knotsvec/vknots/g" *
sed -i "s/innervec/vinner/g" *
sed -i "s/evecvec/vevec/g" *
sed -i "s/evalvec/veval/g" *
sed -i "s/labelvec/vlabel/g" *
sed -i "s/distvec/vdist/g" *
sed -i "s/crossvec/vcross/g" *
sed -i "s/dmatvec/vdmat/g" *
sed -i "s/dsortvec/vdsort/g" *
sed -i "s/xauxvec/vxaux/g" *
sed -i "s/vinvvec/vvinv/g" *
sed -i "s/vinvmat/mvinv/g" *





